// Desarrollado por Jose Eduardo Romero Jimenez
// https://github.com/Edunzz

/**
 * scripts/vendor.mjs — Copia las librerías del navegador desde node_modules a
 * assets/vendor y genera el sprite de iconos. Así el sitio no depende de CDNs
 * y las versiones quedan fijadas por package-lock.json.
 *
 *   node scripts/vendor.mjs
 *
 * El resultado se versiona para que el sitio también funcione publicando
 * directamente desde una rama (sin GitHub Actions).
 */

import { readFile, writeFile, mkdir } from "node:fs/promises";
import { readFileSync } from "node:fs";
import path from "node:path";
import { ROOT, isMain } from "./lib/docs.mjs";
import { LUCIDE_ICONS } from "../assets/js/icons.js";

const VENDOR = path.join(ROOT, "assets", "vendor");
const ICONS = path.join(ROOT, "assets", "icons");
// Algunos paquetes (dompurify) no exportan package.json: se leen desde node_modules.
const pkgDir = (name) => path.join(ROOT, "node_modules", ...name.split("/"));
const version = (name) => JSON.parse(readFileSync(path.join(pkgDir(name), "package.json"), "utf8")).version;

const PRISM_COMPONENTS = ["core", "markup", "css", "clike", "javascript", "typescript", "json", "yaml", "bash", "powershell", "python", "sql", "markdown", "diff", "docker", "ini"];

const stripSourceMap = (text) => text.replace(/\n?\/\/# sourceMappingURL=\S+\s*$/, "\n");

async function copyModule(name, relative, target) {
  const source = await readFile(path.join(pkgDir(name), relative), "utf8");
  await writeFile(path.join(VENDOR, target), stripSourceMap(source), "utf8");
  return { name, version: version(name), file: target };
}

async function buildPrism() {
  const dir = path.join(pkgDir("prismjs"), "components");
  const parts = [`/*! Prism ${version("prismjs")} | MIT | https://prismjs.com — componentes: ${PRISM_COMPONENTS.join(", ")} */`];
  for (const component of PRISM_COMPONENTS) parts.push((await readFile(path.join(dir, `prism-${component}.min.js`), "utf8")).trim());
  await writeFile(path.join(VENDOR, "prism.js"), parts.join("\n") + "\n", "utf8");
  return { name: "prismjs", version: version("prismjs"), file: "prism.js" };
}

async function buildSprite() {
  const lucideDir = path.join(pkgDir("lucide-static"), "icons");
  const symbols = [];
  for (const name of [...LUCIDE_ICONS].sort()) {
    const svg = await readFile(path.join(lucideDir, `${name}.svg`), "utf8").catch(() => {
      throw new Error(`El icono de Lucide «${name}» no existe en lucide-static ${version("lucide-static")}.`);
    });
    const inner = /<svg[^>]*>([\s\S]*?)<\/svg>/.exec(svg)[1].replace(/\s*\n\s*/g, "").trim();
    symbols.push(`<symbol id="${name}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">${inner}</symbol>`);
  }
  const octicon = await readFile(path.join(pkgDir("@primer/octicons"), "build", "svg", "mark-github-24.svg"), "utf8");
  const githubPath = /<path d="([^"]+)"/.exec(octicon)[1];
  symbols.push(`<symbol id="github" viewBox="0 0 24 24"><path fill="currentColor" stroke="none" d="${githubPath}"/></symbol>`);
  symbols.sort((a, b) => /id="([^"]+)"/.exec(a)[1].localeCompare(/id="([^"]+)"/.exec(b)[1]));

  const sprite = [
    '<svg xmlns="http://www.w3.org/2000/svg">',
    `<!-- Generado por scripts/vendor.mjs (Desarrollado por Jose Eduardo Romero Jimenez - https://github.com/Edunzz). Iconos: Lucide ${version("lucide-static")} (ISC) y Octicons ${version("@primer/octicons")} mark-github (MIT). Ver assets/vendor/THIRD_PARTY_NOTICES.md -->`,
    ...symbols,
    "</svg>",
    "",
  ].join("\n");
  await writeFile(path.join(ICONS, "sprite.svg"), sprite, "utf8");
  return symbols.length;
}

async function licenseText(name) {
  for (const file of ["LICENSE", "LICENSE.md", "LICENSE.txt", "license"]) {
    try {
      return (await readFile(path.join(pkgDir(name), file), "utf8")).trim();
    } catch {
      /* siguiente candidato */
    }
  }
  return "(licencia no encontrada en el paquete)";
}

async function writeNotices(packages) {
  const sections = [];
  for (const { name, license, use } of packages) {
    sections.push(`## ${name} ${version(name)} — ${license}\n\n${use}\n\n\`\`\`text\n${await licenseText(name)}\n\`\`\``);
  }
  const text = [
    "# Avisos de terceros · Third-party notices",
    "",
    "Archivos generados por `scripts/vendor.mjs` a partir de `node_modules` (versiones fijadas en `package-lock.json`).",
    "Files generated by `scripts/vendor.mjs` from `node_modules` (versions pinned in `package-lock.json`).",
    "",
    ...sections,
    "",
  ].join("\n");
  await writeFile(path.join(VENDOR, "THIRD_PARTY_NOTICES.md"), text, "utf8");
}

export async function vendor() {
  await mkdir(VENDOR, { recursive: true });
  await mkdir(ICONS, { recursive: true });
  const copied = [
    await copyModule("markdown-it", "dist/browser/markdown-it.esm.min.mjs", "markdown-it.mjs"),
    await copyModule("js-yaml", "dist/browser/js-yaml.esm.min.mjs", "js-yaml.mjs"),
    await copyModule("dompurify", "dist/purify.es.mjs", "purify.mjs"),
    await buildPrism(),
  ];
  const iconCount = await buildSprite();
  await writeNotices([
    { name: "markdown-it", license: "MIT", use: "Render de Markdown (`assets/vendor/markdown-it.mjs`)." },
    { name: "js-yaml", license: "MIT", use: "Lectura del front matter YAML (`assets/vendor/js-yaml.mjs`)." },
    { name: "dompurify", license: "MPL-2.0 OR Apache-2.0", use: "Sanitización del HTML generado (`assets/vendor/purify.mjs`)." },
    { name: "prismjs", license: "MIT", use: "Resaltado de código (`assets/vendor/prism.js`)." },
    { name: "lucide-static", license: "ISC", use: "Iconos del sprite (`assets/icons/sprite.svg`)." },
    { name: "@primer/octicons", license: "MIT", use: "Icono `github` del sprite (`assets/icons/sprite.svg`)." },
  ]);
  return { copied, iconCount };
}

if (isMain(import.meta.url)) {
  const { copied, iconCount } = await vendor();
  for (const item of copied) console.log(`✔ assets/vendor/${item.file}  (${item.name} ${item.version})`);
  console.log(`✔ assets/icons/sprite.svg  (${iconCount} iconos)`);
  console.log("✔ assets/vendor/THIRD_PARTY_NOTICES.md");
}
